### ISSUE TITLE
Validate that Configuration Exists during Config Load

### ISSUE THREAD

**Issue by ak3216** [airshipit/airshipctl#194] opened 2020-04-29 19:01 UTC
**Problem description**
Invalid variable configuration can cause null pointer issues leading to runtime errors (e.g. uninitialized maps).  When configuration is loaded specific sub-command validations are not performed until the sub-command operation.  There is a need to validate that configuration exists at the time it is loaded.
Reference issue #190 - Invalid config could cause runtime error

**Proposed change**
Enhance the airship config load to throw a warning if there is no configuration.

**Potential impacts**
By expanding the pool of upfront validations, we can eliminate runtime errors due to bad configurations at the sub-command level.

**Comment by ian-howell** [comment] 2020-05-18 15:33
I believe this may be implemented already, but I'll take a look prior to closing

**Comment by ian-howell** [comment] 2020-05-18 20:39
Closing as this is a duplicate of https://github.com/airshipit/airshipctl/issues/190

**Closed by ian-howell** 2020-05-18 20:39 UTC
Labels: enhancement, good first issue
