### ISSUE TITLE
Exposure of Argo CLI commands via airshipctl

### ISSUE THREAD

**Issue by singhannie** [airshipit/airshipctl#96] opened 2020-03-07 04:53 UTC
**Problem description (if applicable)**
Airshipctl would offer predefined and curated workflow and would submit workflows to Argo for executation to deploy platform software components via Helm. To manage the submitted Argo workflows, airshipctl needs to be integrated with Argo CLI.

**Proposed change**

Airshipctl needs to integrate directly with Argo CLI to leverage supported capabilities / sub-commands in Argo CLI. Airshipctl willl support following operations on workflow.
- list - List active or deployed workflows
- get - Display details about a workflow
- submit - Submit a workflow (TBD)
- available - List available  workflows to be used by airshipctl
- watch - Watch a workflow until it completes
- delete - Delete a  custom workflow
- terminate - Terminate a workflow
- suspend - Suspend a workflow
- resume - Resume a workflow
- logs - View logs of a workflow
**_Note:_** it needs to be evaluated whether "submit" operation should be exposed, given that execution of custom workflow might not be desired.

RBAC mechanism shall be put in place so that only authorized users are able to check the status of running workflows and no unauthorized user is able to submit any custom workflows to Argo.

it must be validated, that Argo workflow should work smoothly even if chart creates pods with sophisticated capabilities like privileged mode, host networking, local persistent volumes etc, given that leaf level workflows would create an ArmadaCLI pod to apply the chart and Armada would use its own service account to apply the chart, 

**Potential impacts**
It would bring the parity in airshipctl vis-a-vis Argo CLI and would allow management of Argo workflow by airshipctl interface.

**Comment by ian-howell** [comment] 2020-03-13 14:09
I thought we decided to abandon the idea of subclients?

**Comment by singhannie** [comment] 2020-03-18 15:02
@ian-howell , I am not aware of abandoning of the idea of sub-clients. Intent here is to provide a way to human user to manage Argo workflows directly on airshipctl. it can be discussed in the design call for how it would be implemented.

**Comment by ian-howell** [comment] 2020-03-18 15:57
Possible duplicate of https://github.com/airshipit/airshipctl/issues/18. These two issues should be merged/deleted once a design is finalized.

**Closed** 2020-05-13 14:20 UTC
Labels: blocked, cli, design needed, duplicate, enhancement, invalid
