### ISSUE TITLE
airshipctl exits with error when expanding controlplane nodes

### ISSUE THREAD

**Issue by sreejithpunnapuzha** [airshipit/airshipctl#525] opened 2021-04-15 22:00 UTC
when we deploy multi node environment, airshipctl exists with below error when adding second controlplane node

[airshipctl] 2021/04/15 20:50:10 opendev.org/airship/airshipctl@/pkg/events/processor.go:84: Received error when applying resources to kubernetes: polling for status failed: etcdserver: request timed out 
Error events received on channel, errors are: 
[polling for status failed: etcdserver: request timed out]

if we wait for some time, the node come up without issues. this seems to be an issue when second etcd server joins to kubernetes cluster and we have an interim disconnection.

Expectation: 
airshipctl should wait for the etcd server to join successfully with retry and proceed with the deployment

**Comment by jezogwza** [comment] 2021-04-21 14:26
While etcd is coming up, the kubernetes api becomes unresponsive or unavailable for a brief moment. The wit logic in the KubernetesApplye executor is unable to discern, that the api server will be back after a brief moment. This issue is about thinking about whether we need or can enhance the wait logic to understand there could be sporadic periods of unresponsiveness and work through them. Does the wait require a retry logic to work through this?

**Comment by jgu17** [comment] 2021-06-16 23:31
This has becomes a blocking issue for bare metal phase plan because there is no manual wait in the automated phase plan that the user is able to do in v2.0 before run the next script.

**Comment by teoyaomiqui** [comment] 2021-06-17 03:44
> This has becomes a blocking issue for bare metal phase plan because there is no manual wait in the automated phase plan that the user is able to do in v2.0 before run the next script.

If that is so, we should create a separate phase, that actually waits for ETCD to become stable. This can be done really simple by using a generic container and bash script.

**Comment by jezogwza** [comment] 2021-06-17 15:09
This appears to be a duplicate, https://github.com/airshipit/airshipctl/issues/579. There is a patchset associated with it Related PS - https://review.opendev.org/c/airship/airshipctl/+/794087

**Comment by Arvinderpal** [comment] 2021-06-17 16:21
Sorry I missed the discussion on this in the morning call. 
Couple of things come to mind:

1. etcd is very [resource hungry](https://etcd.io/docs/v3.3/op-guide/hardware/). How large is the disk on our control-plane node? I assume disk bandwidth and memory are ample since this is baremetal. 
2. The issue may be caused by our HA load-balancer. What solution are we using? For example, are we using haproxy+VIP in front of our control-plane nodes? We may want to investigate how the LB behaves when new control-plane backends are added. 

In general, intermittent outages like this should not happen. By introducing a wait, I wonder if we're overlooking the underlying problem. For example, will the problem reoccur every time we scale our control-planes up/down?

**Comment by teoyaomiqui** [comment] 2021-06-17 16:24
@Arvinderpal every time we scale up/down with a phase, the phase would have the ability to wait for, etc to get back to normal, scale up-down of databases is a procedure that usually requires extra steps to wait for synchronization etcd..

**Comment by Arvinderpal** [comment] 2021-06-17 16:36
Yes, but etcd is designed to handle member additions/removals gracefully. If it's going down every time membership changes then something is clearly wrong.

**Comment by teoyaomiqui** [comment] 2021-06-17 16:54
You are right, but adding members to an existing cluster with size 1 is something different than adding members to a 3 node cluster.

The balancing may be the issue here as well, definitely worth investigating

**Comment by Arvinderpal** [comment] 2021-06-23 15:40
FYI, I came across this issue recently. https://github.com/kubernetes-sigs/cluster-api/issues/2535
But you're assumption seems correct -- there can be a temporary disruption when scaling from 1 -> 2 control-planes. Clusterctl handles this through a mix of wait and retry logic. I think we should do the same in airshipctl.

**Comment by raliev12** [comment] 2021-06-24 17:42
I believe we've already implemented retry logic for "request timed out" polling error, which is important. I'm trying to modify wait part accordingly.

**Comment by mf4716** [comment] 2021-06-28 16:22
Related PS to address issue:  https://review.opendev.org/c/airship/airshipctl/+/794087 .  Can close issue.

**Comment by ak3216** [comment] 2021-06-28 16:22
Closing per above patchset

**Closed by ak3216** 2021-06-28 16:22 UTC
Labels: 4-CI/CD, bug, design needed, priority/medium
