### ISSUE TITLE
AIAP: Investigate what causes the `tty` setting to be required for some deployments

### ISSUE THREAD

**Issue by ian-howell** [airshipit/airshipctl#625] opened 2021-08-31 16:18 UTC
Dependent upon the environment in which AIAP is deployed to, the `infra-builder` container will occasionally fail when trying to create libvirt objects with the following error message:

```
TASK [build-infra : virt_pool] *************************************************
failed: [localhost] (item=default) => {"ansible_loop_var": "item", "changed": false, "item": "default", "msg": "Failed to connect socket to /var/run/libvirt/libvirt-sock: Connection refused"}
PLAY RECAP *********************************************************************
localhost                  : ok=3    changed=2    unreachable=0    failed=1    skipped=0    rescued=0 
```

This error can be bypassed by setting the `tty` flag of the `libvirt` container to `true`, as seen here: https://github.com/airshipit/airshipctl/blob/4750ab169cdb76fd5d5fc704e2b4ec87c03a745f/tools/airship-in-a-pod/examples/base/airship-in-a-pod.yaml#L27

The closing criteria for this issue is to identify the root cause of this error.

Note that most environments do not elicit this behavior; steps to reproduce and environment details will be discussed in the comment section of this issue.

**Comment by sanjib-35** [comment] 2021-11-12 15:43
please assign to me

**Comment by sanjib-35** [comment] 2021-11-24 09:39
Tried to deploy AIAP multiple times on local VM and could not reproduce the same issue.
As discussed with Ian, we can close this issue.

**Closed** 2021-11-24 15:26 UTC
Labels: bug, priority/low
