### ISSUE TITLE
Replace CLI flags with configuration data for `airshipctl bootstrap remotedirect`

### ISSUE THREAD

**Issue by ianpittwood** [airshipit/airshipctl#23] opened 2020-02-10 21:03 UTC
**Problem description (if applicable)**
The original implementation of `airshipctl bootstrap remotedirect` occurred before the implementation of configurations in airshipctl. As a placeholder, CLI flags were used to testing and POC for the command.

**Proposed change**
CLI flags should be replaced with calls to the airshipctl configuration data for any data used that is stored there.

Source: TODO, cmd/bootstrap/bootstrap_remotedirect.go, L22 & L62

**Comment by jgu17** [comment] 2020-02-11 15:13
@ianpittwood I'll take a look at it if no one has started on it yet

**Comment by drewwalters96** [comment] 2020-02-11 15:43
@jgu17 @ianpittwood I believe this is a duplicate of #7.

@dukov [merged](https://review.opendev.org/705890) this already

**Closed by drewwalters96** 2020-02-11 15:43 UTC
Labels: cli, component/bootstrap, enhancement, good first issue, sig/bootstrap
