### ISSUE TITLE
Refactor baremetal isogen to airshipctl image build

### ISSUE THREAD

**Issue by lb4368** [airshipit/airshipctl#251] opened 2020-05-27 13:31 UTC
**Problem description (if applicable)**
Current airshipctl baremetal isogen command is too specific to baremetal ISO.  Need a more generic image builder command.

**Proposed change**
With the integration of Image Builder issue #248 , refactor airshipctl baremetal isogen command to airshipctl image build (or something else).

**Comment by sirajyasin** [comment] 2020-05-27 14:15
I can work on this issue if no one has started yet.

**Comment by sreejithpunnapuzha** [comment] 2020-05-27 14:17
@sirajyasin all yours..

**Comment by sirajyasin** [comment] 2020-06-23 14:11
The issue is fixed in this PS https://review.opendev.org/#/c/731597/ and the same is already merged. Not sure why the bot did not autoclose this issue.
This is can be marked closed.

**Comment by ak3216** [comment] 2020-07-06 17:29
Closing per Siraj

**Closed by ak3216** 2020-07-06 17:29 UTC
Labels: enhancement, good first issue
