### ISSUE TITLE
Workflow command

### ISSUE THREAD

**Issue by drewwalters96** [airshipit/airshipctl#18] opened 2020-02-10 19:36 UTC
**Problem description (if applicable)**
The airshipctl client needs the ability to manage workflows using the Argo Workflows wrapper.

**Proposed change**
This is an epic; issues will be filed later with more details.

**Comment by drewwalters96** [comment] 2020-02-10 19:42
[POC](https://review.opendev.org/702475)

**Comment by ian-howell** [comment] 2020-03-18 15:58
Possible duplicate of #96. These two issues should be merged/deleted once a design is finalized.

**Comment by jezogwza** [comment] 2020-05-13 14:24
We are no longer implementing the workflow module

**Closed by jezogwza** 2020-05-13 14:24 UTC
Labels: invalid
