### ISSUE TITLE
Add selector abstraction to document/bundle interface

### ISSUE THREAD

**Issue by teoyaomiqui** [airshipit/airshipctl#60] opened 2020-02-21 21:10 UTC
**Problem description (if applicable)**
Right now to use Select method of bundle interface we need to use "sigs.k8s.io/kustomize/v3/pkg/types" package type Selector. Before too many parts of code start depending on particular kustomize type I suggest we add additional abstraction layer for Selector interface, this way we will have only one place of entry to kustomize, which would be document package.

**Proposed change**
Develop selector abstraction and add it to document package.

**Potential impacts**
None

**Comment by alanmeadows** [comment] 2020-02-21 21:40
@teoyaomiqui I think this is a duplicate of https://github.com/airshipit/airshipctl/issues/11

**Comment by teoyaomiqui** [comment] 2020-02-21 22:03
@alanmeadows yes, didn't find it myself, thanks

**Comment by ianpittwood** [comment] 2020-02-24 15:15
Closed as duplicate

**Closed by ianpittwood** 2020-02-24 15:15 UTC
Labels: duplicate, enhancement
